# Generated by Django 5.1.7 on 2025-03-11 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('pizza_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(70, message='Quantity cannot exceed 70.'), django.core.validators.MinValueValidator(1, message='Quantity must be at least 1.')])),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
